# Generated by Django 3.2.3 on 2022-02-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
