# Generated by Django 3.2.3 on 2022-02-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservation_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_number', models.IntegerField()),
                ('delay', models.IntegerField()),
            ],
        ),
    ]
