# Generated by Django 3.2.3 on 2022-02-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_text',
            field=models.CharField(default='Yes', max_length=200),
            preserve_default=False,
        ),
    ]
