# Generated by Django 3.2.3 on 2022-02-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_messages_message_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
