# Generated by Django 3.2.3 on 2022-02-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220218_2337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Waitlisst',
        ),
    ]
