# Generated by Django 3.2.3 on 2022-02-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_reservation_waitlisst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waitlisst',
            new_name='Waitlist',
        ),
    ]
