# Generated by Django 3.2.12 on 2022-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_waitlisst_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='time_message_sent',
            field=models.DateTimeField(null=True),
        ),
    ]
