# Generated by Django 3.2.12 on 2022-03-16 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_reservation_phone_alter_waitlist_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='time_message_sent',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 17, 18, 58, 232781, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
