# Generated by Django 3.2.12 on 2022-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220316_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddField(
            model_name='message',
            name='message_context',
            field=models.CharField(default='Message sent when table is ready', max_length=200),
            preserve_default=False,
        ),
    ]
