# Generated by Django 3.2.12 on 2022-03-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_waitlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='timecreated',
            field=models.TimeField(default=datetime.datetime(2022, 3, 16, 22, 26, 54, 705446)),
        ),
    ]
