# Generated by Django 3.2.12 on 2022-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220316_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
