# Generated by Django 3.2.12 on 2022-03-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_waitlist_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='date',
        ),
    ]
